import Logo from './svg/logo3.svg';

const Images = {
  splashScreen: require('./img/splashscreen.png'),
  warranty: require('./img/warranty.png'),
  home: require('./img/home.png'),
  home2: require('./img/home2.png'),
  chat: require('./img/chat.png'),
  chat2: require('./img/chat2.png'),
  order: require('./img/order.png'),
  order2: require('./img/order2.png'),
  point: require('./img/point.png'),
  point2: require('./img/point2.png'),
  user: require('./img/user.png'),
  user2: require('./img/user2.png'),
  logoGiaTien: require('./img/logoGiaTien.png'),
  logoTransparent: require('./img/logo_transparent.png'),
  loginGoogle: require('./img/loginGoogle.png'),
  IconProduct: require('./img/IconProduct.png'),
  technicalsupport: require('./img/technical-support.png'),
  coupon: require('./img/coupon.png'),
  bannerSale: require('./img/bannerSale.png'),
  newspaper: require('./img/newspaper.png'),
  phone: require('./img/phone.png'),
  iconComment: require('./img/iconComment.png'),
  gps: require('./img/gps.png'),
  imgHeader: require('./img/imgHeader.png'),
  knoob: require('./img/knoob.png'),
  borderWheel: require('./img/borderwheel.png'),
  money: require('./img/money.png'),
  card: require('./img/card.png'),
  camera: require('./img/camera.png'),
  history: require('./img/history.png'),
  back: require('./img/back.png'),
  imgProfile: require('./img/imgProfile.png'),
  imgNotifi: require('./img/imgNotifi.png'),
  logoNews: require('./img/logoNews.png'),
  imageTest: require('./img/imageTest.png'),
  Iconmaterialhistory: require('./img/Iconmaterial-history.png'),
  addOrder: require('./img/addOrder.png'),
  binIcon: require('./img/binIcon.png'),
  radio: require('./img/radio.png'),
  radio1: require('./img/radio1.png'),
  ip11promax: require('./img/ip11promax.png'),
  logoGiaTiensvg: Logo,
  logo: require('./img/logo.jpg'),
  logoHor: require('./img/logoHor.jpg'),
};
export default Images;
